# Build the Go sidecar
go build -o ../bin/sidecar ./cmd/sidecar/main.go

# Or cross-compile for different platforms
# GOOS=linux GOARCH=amd64 go build -o ../bin/sidecar-linux-amd64 ./cmd/sidecar/main.go
# GOOS=linux GOARCH=arm64 go build -o ../bin/sidecar-linux-arm64 ./cmd/sidecar/main.go
