// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sidecar.proto

package sidecar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyMode int32

const (
	ProxyMode_DIRECT       ProxyMode = 0
	ProxyMode_SOCKS5       ProxyMode = 1
	ProxyMode_HTTP_CONNECT ProxyMode = 2
)

// Enum value maps for ProxyMode.
var (
	ProxyMode_name = map[int32]string{
		0: "DIRECT",
		1: "SOCKS5",
		2: "HTTP_CONNECT",
	}
	ProxyMode_value = map[string]int32{
		"DIRECT":       0,
		"SOCKS5":       1,
		"HTTP_CONNECT": 2,
	}
)

func (x ProxyMode) Enum() *ProxyMode {
	p := new(ProxyMode)
	*p = x
	return p
}

func (x ProxyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sidecar_proto_enumTypes[0].Descriptor()
}

func (ProxyMode) Type() protoreflect.EnumType {
	return &file_proto_sidecar_proto_enumTypes[0]
}

func (x ProxyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyMode.Descriptor instead.
func (ProxyMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{0}
}

type DownloadRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl         string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	BrowserPreset     string                 `protobuf:"bytes,2,opt,name=browser_preset,json=browserPreset,proto3" json:"browser_preset,omitempty"`       // chrome_124, firefox_120, safari_17, etc.
	TcpTtl            int32                  `protobuf:"varint,3,opt,name=tcp_ttl,json=tcpTtl,proto3" json:"tcp_ttl,omitempty"`                           // IP TTL (32-255)
	TcpMss            int32                  `protobuf:"varint,4,opt,name=tcp_mss,json=tcpMss,proto3" json:"tcp_mss,omitempty"`                           // TCP MSS (1200-1500)
	TcpWindowScale    int32                  `protobuf:"varint,5,opt,name=tcp_window_scale,json=tcpWindowScale,proto3" json:"tcp_window_scale,omitempty"` // Window Scale factor (0-14)
	TcpSack           bool                   `protobuf:"varint,6,opt,name=tcp_sack,json=tcpSack,proto3" json:"tcp_sack,omitempty"`                        // Selective ACK permitted
	TcpTimestamps     bool                   `protobuf:"varint,7,opt,name=tcp_timestamps,json=tcpTimestamps,proto3" json:"tcp_timestamps,omitempty"`      // TCP Timestamps option
	TcpWindowSize     int32                  `protobuf:"varint,8,opt,name=tcp_window_size,json=tcpWindowSize,proto3" json:"tcp_window_size,omitempty"`    // TCP Initial Window Size
	UserAgent         string                 `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	EnableGrease      bool                   `protobuf:"varint,10,opt,name=enable_grease,json=enableGrease,proto3" json:"enable_grease,omitempty"`
	H2WindowIncrement int32                  `protobuf:"varint,11,opt,name=h2_window_increment,json=h2WindowIncrement,proto3" json:"h2_window_increment,omitempty"` // HTTP/2 SETTINGS initial window size
	// IP 隐藏 / 出口配置
	Proxy *ProxyConfig `protobuf:"bytes,12,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Dns   *DnsConfig   `protobuf:"bytes,13,opt,name=dns,proto3" json:"dns,omitempty"`
	// CDN 优化引擎
	CdnType       string `protobuf:"bytes,14,opt,name=cdn_type,json=cdnType,proto3" json:"cdn_type,omitempty"` // "cloudflare", "akamai", "incapsula", "custom", 空=不优化
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *DownloadRequest) GetBrowserPreset() string {
	if x != nil {
		return x.BrowserPreset
	}
	return ""
}

func (x *DownloadRequest) GetTcpTtl() int32 {
	if x != nil {
		return x.TcpTtl
	}
	return 0
}

func (x *DownloadRequest) GetTcpMss() int32 {
	if x != nil {
		return x.TcpMss
	}
	return 0
}

func (x *DownloadRequest) GetTcpWindowScale() int32 {
	if x != nil {
		return x.TcpWindowScale
	}
	return 0
}

func (x *DownloadRequest) GetTcpSack() bool {
	if x != nil {
		return x.TcpSack
	}
	return false
}

func (x *DownloadRequest) GetTcpTimestamps() bool {
	if x != nil {
		return x.TcpTimestamps
	}
	return false
}

func (x *DownloadRequest) GetTcpWindowSize() int32 {
	if x != nil {
		return x.TcpWindowSize
	}
	return 0
}

func (x *DownloadRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *DownloadRequest) GetEnableGrease() bool {
	if x != nil {
		return x.EnableGrease
	}
	return false
}

func (x *DownloadRequest) GetH2WindowIncrement() int32 {
	if x != nil {
		return x.H2WindowIncrement
	}
	return 0
}

func (x *DownloadRequest) GetProxy() *ProxyConfig {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *DownloadRequest) GetDns() *DnsConfig {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *DownloadRequest) GetCdnType() string {
	if x != nil {
		return x.CdnType
	}
	return ""
}

type ProxyConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mode             ProxyMode              `protobuf:"varint,1,opt,name=mode,proto3,enum=sidecar.ProxyMode" json:"mode,omitempty"`
	Nodes            []*ProxyNode           `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`                                               // 代理节点列表，为空则直连
	RotationStrategy string                 `protobuf:"bytes,3,opt,name=rotation_strategy,json=rotationStrategy,proto3" json:"rotation_strategy,omitempty"` // "round_robin", "random", "lowest_latency"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_proto_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyConfig) GetMode() ProxyMode {
	if x != nil {
		return x.Mode
	}
	return ProxyMode_DIRECT
}

func (x *ProxyConfig) GetNodes() []*ProxyNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ProxyConfig) GetRotationStrategy() string {
	if x != nil {
		return x.RotationStrategy
	}
	return ""
}

type ProxyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	BindIp        string                 `protobuf:"bytes,5,opt,name=bind_ip,json=bindIp,proto3" json:"bind_ip,omitempty"` // 本地绑定 IP（多网卡多 IP 场景）
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`               // 节点地域标识
	Weight        int32                  `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyNode) Reset() {
	*x = ProxyNode{}
	mi := &file_proto_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyNode) ProtoMessage() {}

func (x *ProxyNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyNode.ProtoReflect.Descriptor instead.
func (*ProxyNode) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyNode) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProxyNode) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyNode) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyNode) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProxyNode) GetBindIp() string {
	if x != nil {
		return x.BindIp
	}
	return ""
}

func (x *ProxyNode) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProxyNode) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type DnsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Servers       []string               `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Parallel      bool                   `protobuf:"varint,4,opt,name=parallel,proto3" json:"parallel,omitempty"`
	CacheEnabled  bool                   `protobuf:"varint,5,opt,name=cache_enabled,json=cacheEnabled,proto3" json:"cache_enabled,omitempty"`
	HostsOverride string                 `protobuf:"bytes,6,opt,name=hosts_override,json=hostsOverride,proto3" json:"hosts_override,omitempty"`
	LbStrategy    string                 `protobuf:"bytes,7,opt,name=lb_strategy,json=lbStrategy,proto3" json:"lb_strategy,omitempty"` // "fastest", "round_robin", "random", "priority"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsConfig) Reset() {
	*x = DnsConfig{}
	mi := &file_proto_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsConfig) ProtoMessage() {}

func (x *DnsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsConfig.ProtoReflect.Descriptor instead.
func (*DnsConfig) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *DnsConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DnsConfig) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *DnsConfig) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *DnsConfig) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

func (x *DnsConfig) GetCacheEnabled() bool {
	if x != nil {
		return x.CacheEnabled
	}
	return false
}

func (x *DnsConfig) GetHostsOverride() string {
	if x != nil {
		return x.HostsOverride
	}
	return ""
}

func (x *DnsConfig) GetLbStrategy() string {
	if x != nil {
		return x.LbStrategy
	}
	return ""
}

type DownloadEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*DownloadEvent_Log
	//	*DownloadEvent_Progress
	//	*DownloadEvent_State
	//	*DownloadEvent_Error
	//	*DownloadEvent_TlsInfo
	//	*DownloadEvent_TcpInfo
	//	*DownloadEvent_Complete
	Event         isDownloadEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadEvent) Reset() {
	*x = DownloadEvent{}
	mi := &file_proto_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadEvent) ProtoMessage() {}

func (x *DownloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadEvent.ProtoReflect.Descriptor instead.
func (*DownloadEvent) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadEvent) GetEvent() isDownloadEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *DownloadEvent) GetLog() *LogEvent {
	if x != nil {
		if x, ok := x.Event.(*DownloadEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *DownloadEvent) GetProgress() *ProgressEvent {
	if x != nil {
		if x, ok := x.Event.(*DownloadEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *DownloadEvent) GetState() *StateEvent {
	if x != nil {
		if x, ok := x.Event.(*DownloadEvent_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *DownloadEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*DownloadEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *DownloadEvent) GetTlsInfo() *TlsInfo {
	if x != nil {
		if x, ok := x.Event.(*DownloadEvent_TlsInfo); ok {
			return x.TlsInfo
		}
	}
	return nil
}

func (x *DownloadEvent) GetTcpInfo() *TcpInfo {
	if x != nil {
		if x, ok := x.Event.(*DownloadEvent_TcpInfo); ok {
			return x.TcpInfo
		}
	}
	return nil
}

func (x *DownloadEvent) GetComplete() *CompleteEvent {
	if x != nil {
		if x, ok := x.Event.(*DownloadEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isDownloadEvent_Event interface {
	isDownloadEvent_Event()
}

type DownloadEvent_Log struct {
	Log *LogEvent `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type DownloadEvent_Progress struct {
	Progress *ProgressEvent `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type DownloadEvent_State struct {
	State *StateEvent `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

type DownloadEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type DownloadEvent_TlsInfo struct {
	TlsInfo *TlsInfo `protobuf:"bytes,5,opt,name=tls_info,json=tlsInfo,proto3,oneof"`
}

type DownloadEvent_TcpInfo struct {
	TcpInfo *TcpInfo `protobuf:"bytes,6,opt,name=tcp_info,json=tcpInfo,proto3,oneof"`
}

type DownloadEvent_Complete struct {
	Complete *CompleteEvent `protobuf:"bytes,7,opt,name=complete,proto3,oneof"`
}

func (*DownloadEvent_Log) isDownloadEvent_Event() {}

func (*DownloadEvent_Progress) isDownloadEvent_Event() {}

func (*DownloadEvent_State) isDownloadEvent_Event() {}

func (*DownloadEvent_Error) isDownloadEvent_Event() {}

func (*DownloadEvent_TlsInfo) isDownloadEvent_Event() {}

func (*DownloadEvent_TcpInfo) isDownloadEvent_Event() {}

func (*DownloadEvent_Complete) isDownloadEvent_Event() {}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_proto_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      float64                `protobuf:"fixed64,1,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	SpeedMbps     float64                `protobuf:"fixed64,2,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	ReceivedBytes int64                  `protobuf:"varint,3,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_proto_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressEvent) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressEvent) GetSpeedMbps() float64 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

func (x *ProgressEvent) GetReceivedBytes() int64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *ProgressEvent) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type StateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "handshake", "downloading", "completed", "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEvent) Reset() {
	*x = StateEvent{}
	mi := &file_proto_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEvent) ProtoMessage() {}

func (x *StateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEvent.ProtoReflect.Descriptor instead.
func (*StateEvent) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *StateEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type TlsInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ja4            string                 `protobuf:"bytes,1,opt,name=ja4,proto3" json:"ja4,omitempty"`
	Ja3            string                 `protobuf:"bytes,2,opt,name=ja3,proto3" json:"ja3,omitempty"`
	CipherSuite    string                 `protobuf:"bytes,3,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"`
	TlsVersion     string                 `protobuf:"bytes,4,opt,name=tls_version,json=tlsVersion,proto3" json:"tls_version,omitempty"`
	Alpn           string                 `protobuf:"bytes,5,opt,name=alpn,proto3" json:"alpn,omitempty"`
	GreaseDetected bool                   `protobuf:"varint,6,opt,name=grease_detected,json=greaseDetected,proto3" json:"grease_detected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TlsInfo) Reset() {
	*x = TlsInfo{}
	mi := &file_proto_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsInfo) ProtoMessage() {}

func (x *TlsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsInfo.ProtoReflect.Descriptor instead.
func (*TlsInfo) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *TlsInfo) GetJa4() string {
	if x != nil {
		return x.Ja4
	}
	return ""
}

func (x *TlsInfo) GetJa3() string {
	if x != nil {
		return x.Ja3
	}
	return ""
}

func (x *TlsInfo) GetCipherSuite() string {
	if x != nil {
		return x.CipherSuite
	}
	return ""
}

func (x *TlsInfo) GetTlsVersion() string {
	if x != nil {
		return x.TlsVersion
	}
	return ""
}

func (x *TlsInfo) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *TlsInfo) GetGreaseDetected() bool {
	if x != nil {
		return x.GreaseDetected
	}
	return false
}

type TcpInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActualTtl         int32                  `protobuf:"varint,1,opt,name=actual_ttl,json=actualTtl,proto3" json:"actual_ttl,omitempty"`
	ActualMss         int32                  `protobuf:"varint,2,opt,name=actual_mss,json=actualMss,proto3" json:"actual_mss,omitempty"`
	ActualWindowScale int32                  `protobuf:"varint,3,opt,name=actual_window_scale,json=actualWindowScale,proto3" json:"actual_window_scale,omitempty"`
	ActualSack        bool                   `protobuf:"varint,4,opt,name=actual_sack,json=actualSack,proto3" json:"actual_sack,omitempty"`
	ActualTimestamps  bool                   `protobuf:"varint,5,opt,name=actual_timestamps,json=actualTimestamps,proto3" json:"actual_timestamps,omitempty"`
	SourceIp          string                 `protobuf:"bytes,6,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestIp            string                 `protobuf:"bytes,7,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	ProxyUsed         string                 `protobuf:"bytes,8,opt,name=proxy_used,json=proxyUsed,proto3" json:"proxy_used,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TcpInfo) Reset() {
	*x = TcpInfo{}
	mi := &file_proto_sidecar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpInfo) ProtoMessage() {}

func (x *TcpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpInfo.ProtoReflect.Descriptor instead.
func (*TcpInfo) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{10}
}

func (x *TcpInfo) GetActualTtl() int32 {
	if x != nil {
		return x.ActualTtl
	}
	return 0
}

func (x *TcpInfo) GetActualMss() int32 {
	if x != nil {
		return x.ActualMss
	}
	return 0
}

func (x *TcpInfo) GetActualWindowScale() int32 {
	if x != nil {
		return x.ActualWindowScale
	}
	return 0
}

func (x *TcpInfo) GetActualSack() bool {
	if x != nil {
		return x.ActualSack
	}
	return false
}

func (x *TcpInfo) GetActualTimestamps() bool {
	if x != nil {
		return x.ActualTimestamps
	}
	return false
}

func (x *TcpInfo) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *TcpInfo) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *TcpInfo) GetProxyUsed() string {
	if x != nil {
		return x.ProxyUsed
	}
	return ""
}

type CompleteEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes      int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AvgSpeedMbps    float64                `protobuf:"fixed64,3,opt,name=avg_speed_mbps,json=avgSpeedMbps,proto3" json:"avg_speed_mbps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteEvent) Reset() {
	*x = CompleteEvent{}
	mi := &file_proto_sidecar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteEvent) ProtoMessage() {}

func (x *CompleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteEvent.ProtoReflect.Descriptor instead.
func (*CompleteEvent) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteEvent) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *CompleteEvent) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CompleteEvent) GetAvgSpeedMbps() float64 {
	if x != nil {
		return x.AvgSpeedMbps
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{12}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_sidecar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{14}
}

type PresetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       []*Preset              `protobuf:"bytes,1,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetList) Reset() {
	*x = PresetList{}
	mi := &file_proto_sidecar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetList) ProtoMessage() {}

func (x *PresetList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetList.ProtoReflect.Descriptor instead.
func (*PresetList) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{15}
}

func (x *PresetList) GetPresets() []*Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type Preset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserAgent       string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Ja3             string                 `protobuf:"bytes,4,opt,name=ja3,proto3" json:"ja3,omitempty"`
	Ja4             string                 `protobuf:"bytes,5,opt,name=ja4,proto3" json:"ja4,omitempty"`
	DefaultH2Window int32                  `protobuf:"varint,6,opt,name=default_h2_window,json=defaultH2Window,proto3" json:"default_h2_window,omitempty"`
	HasGrease       bool                   `protobuf:"varint,7,opt,name=has_grease,json=hasGrease,proto3" json:"has_grease,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_proto_sidecar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{16}
}

func (x *Preset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Preset) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Preset) GetJa3() string {
	if x != nil {
		return x.Ja3
	}
	return ""
}

func (x *Preset) GetJa4() string {
	if x != nil {
		return x.Ja4
	}
	return ""
}

func (x *Preset) GetDefaultH2Window() int32 {
	if x != nil {
		return x.DefaultH2Window
	}
	return 0
}

func (x *Preset) GetHasGrease() bool {
	if x != nil {
		return x.HasGrease
	}
	return false
}

var File_proto_sidecar_proto protoreflect.FileDescriptor

const file_proto_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sidecar.proto\x12\asidecar\"\xfe\x03\n" +
	"\x0fDownloadRequest\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12%\n" +
	"\x0ebrowser_preset\x18\x02 \x01(\tR\rbrowserPreset\x12\x17\n" +
	"\atcp_ttl\x18\x03 \x01(\x05R\x06tcpTtl\x12\x17\n" +
	"\atcp_mss\x18\x04 \x01(\x05R\x06tcpMss\x12(\n" +
	"\x10tcp_window_scale\x18\x05 \x01(\x05R\x0etcpWindowScale\x12\x19\n" +
	"\btcp_sack\x18\x06 \x01(\bR\atcpSack\x12%\n" +
	"\x0etcp_timestamps\x18\a \x01(\bR\rtcpTimestamps\x12&\n" +
	"\x0ftcp_window_size\x18\b \x01(\x05R\rtcpWindowSize\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x12#\n" +
	"\renable_grease\x18\n" +
	" \x01(\bR\fenableGrease\x12.\n" +
	"\x13h2_window_increment\x18\v \x01(\x05R\x11h2WindowIncrement\x12*\n" +
	"\x05proxy\x18\f \x01(\v2\x14.sidecar.ProxyConfigR\x05proxy\x12$\n" +
	"\x03dns\x18\r \x01(\v2\x12.sidecar.DnsConfigR\x03dns\x12\x19\n" +
	"\bcdn_type\x18\x0e \x01(\tR\acdnType\"\x8c\x01\n" +
	"\vProxyConfig\x12&\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x12.sidecar.ProxyModeR\x04mode\x12(\n" +
	"\x05nodes\x18\x02 \x03(\v2\x12.sidecar.ProxyNodeR\x05nodes\x12+\n" +
	"\x11rotation_strategy\x18\x03 \x01(\tR\x10rotationStrategy\"\xb4\x01\n" +
	"\tProxyNode\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x17\n" +
	"\abind_ip\x18\x05 \x01(\tR\x06bindIp\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x16\n" +
	"\x06weight\x18\a \x01(\x05R\x06weight\"\xe7\x01\n" +
	"\tDnsConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aservers\x18\x02 \x03(\tR\aservers\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12\x1a\n" +
	"\bparallel\x18\x04 \x01(\bR\bparallel\x12#\n" +
	"\rcache_enabled\x18\x05 \x01(\bR\fcacheEnabled\x12%\n" +
	"\x0ehosts_override\x18\x06 \x01(\tR\rhostsOverride\x12\x1f\n" +
	"\vlb_strategy\x18\a \x01(\tR\n" +
	"lbStrategy\"\xe3\x02\n" +
	"\rDownloadEvent\x12%\n" +
	"\x03log\x18\x01 \x01(\v2\x11.sidecar.LogEventH\x00R\x03log\x124\n" +
	"\bprogress\x18\x02 \x01(\v2\x16.sidecar.ProgressEventH\x00R\bprogress\x12+\n" +
	"\x05state\x18\x03 \x01(\v2\x13.sidecar.StateEventH\x00R\x05state\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x13.sidecar.ErrorEventH\x00R\x05error\x12-\n" +
	"\btls_info\x18\x05 \x01(\v2\x10.sidecar.TlsInfoH\x00R\atlsInfo\x12-\n" +
	"\btcp_info\x18\x06 \x01(\v2\x10.sidecar.TcpInfoH\x00R\atcpInfo\x124\n" +
	"\bcomplete\x18\a \x01(\v2\x16.sidecar.CompleteEventH\x00R\bcompleteB\a\n" +
	"\x05event\"$\n" +
	"\bLogEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x92\x01\n" +
	"\rProgressEvent\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x01R\bprogress\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\x02 \x01(\x01R\tspeedMbps\x12%\n" +
	"\x0ereceived_bytes\x18\x03 \x01(\x03R\rreceivedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\"\"\n" +
	"\n" +
	"StateEvent\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\":\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xae\x01\n" +
	"\aTlsInfo\x12\x10\n" +
	"\x03ja4\x18\x01 \x01(\tR\x03ja4\x12\x10\n" +
	"\x03ja3\x18\x02 \x01(\tR\x03ja3\x12!\n" +
	"\fcipher_suite\x18\x03 \x01(\tR\vcipherSuite\x12\x1f\n" +
	"\vtls_version\x18\x04 \x01(\tR\n" +
	"tlsVersion\x12\x12\n" +
	"\x04alpn\x18\x05 \x01(\tR\x04alpn\x12'\n" +
	"\x0fgrease_detected\x18\x06 \x01(\bR\x0egreaseDetected\"\x9a\x02\n" +
	"\aTcpInfo\x12\x1d\n" +
	"\n" +
	"actual_ttl\x18\x01 \x01(\x05R\tactualTtl\x12\x1d\n" +
	"\n" +
	"actual_mss\x18\x02 \x01(\x05R\tactualMss\x12.\n" +
	"\x13actual_window_scale\x18\x03 \x01(\x05R\x11actualWindowScale\x12\x1f\n" +
	"\vactual_sack\x18\x04 \x01(\bR\n" +
	"actualSack\x12+\n" +
	"\x11actual_timestamps\x18\x05 \x01(\bR\x10actualTimestamps\x12\x1b\n" +
	"\tsource_ip\x18\x06 \x01(\tR\bsourceIp\x12\x17\n" +
	"\adest_ip\x18\a \x01(\tR\x06destIp\x12\x1d\n" +
	"\n" +
	"proxy_used\x18\b \x01(\tR\tproxyUsed\"\x81\x01\n" +
	"\rCompleteEvent\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x01R\x0fdurationSeconds\x12$\n" +
	"\x0eavg_speed_mbps\x18\x03 \x01(\x01R\favgSpeedMbps\"\r\n" +
	"\vPingRequest\"O\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\"\a\n" +
	"\x05Empty\"7\n" +
	"\n" +
	"PresetList\x12)\n" +
	"\apresets\x18\x01 \x03(\v2\x0f.sidecar.PresetR\apresets\"\xba\x01\n" +
	"\x06Preset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x10\n" +
	"\x03ja3\x18\x04 \x01(\tR\x03ja3\x12\x10\n" +
	"\x03ja4\x18\x05 \x01(\tR\x03ja4\x12*\n" +
	"\x11default_h2_window\x18\x06 \x01(\x05R\x0fdefaultH2Window\x12\x1d\n" +
	"\n" +
	"has_grease\x18\a \x01(\bR\thasGrease*5\n" +
	"\tProxyMode\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\n" +
	"\n" +
	"\x06SOCKS5\x10\x01\x12\x10\n" +
	"\fHTTP_CONNECT\x10\x022\xbf\x01\n" +
	"\x15FingerprintDownloader\x12>\n" +
	"\bDownload\x12\x18.sidecar.DownloadRequest\x1a\x16.sidecar.DownloadEvent0\x01\x123\n" +
	"\x04Ping\x12\x14.sidecar.PingRequest\x1a\x15.sidecar.PingResponse\x121\n" +
	"\n" +
	"GetPresets\x12\x0e.sidecar.Empty\x1a\x13.sidecar.PresetListB6Z4github.com/tcp-fingerprint/sidecar/pkg/proto/sidecarb\x06proto3"

var (
	file_proto_sidecar_proto_rawDescOnce sync.Once
	file_proto_sidecar_proto_rawDescData []byte
)

func file_proto_sidecar_proto_rawDescGZIP() []byte {
	file_proto_sidecar_proto_rawDescOnce.Do(func() {
		file_proto_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sidecar_proto_rawDesc), len(file_proto_sidecar_proto_rawDesc)))
	})
	return file_proto_sidecar_proto_rawDescData
}

var file_proto_sidecar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_sidecar_proto_goTypes = []any{
	(ProxyMode)(0),          // 0: sidecar.ProxyMode
	(*DownloadRequest)(nil), // 1: sidecar.DownloadRequest
	(*ProxyConfig)(nil),     // 2: sidecar.ProxyConfig
	(*ProxyNode)(nil),       // 3: sidecar.ProxyNode
	(*DnsConfig)(nil),       // 4: sidecar.DnsConfig
	(*DownloadEvent)(nil),   // 5: sidecar.DownloadEvent
	(*LogEvent)(nil),        // 6: sidecar.LogEvent
	(*ProgressEvent)(nil),   // 7: sidecar.ProgressEvent
	(*StateEvent)(nil),      // 8: sidecar.StateEvent
	(*ErrorEvent)(nil),      // 9: sidecar.ErrorEvent
	(*TlsInfo)(nil),         // 10: sidecar.TlsInfo
	(*TcpInfo)(nil),         // 11: sidecar.TcpInfo
	(*CompleteEvent)(nil),   // 12: sidecar.CompleteEvent
	(*PingRequest)(nil),     // 13: sidecar.PingRequest
	(*PingResponse)(nil),    // 14: sidecar.PingResponse
	(*Empty)(nil),           // 15: sidecar.Empty
	(*PresetList)(nil),      // 16: sidecar.PresetList
	(*Preset)(nil),          // 17: sidecar.Preset
}
var file_proto_sidecar_proto_depIdxs = []int32{
	2,  // 0: sidecar.DownloadRequest.proxy:type_name -> sidecar.ProxyConfig
	4,  // 1: sidecar.DownloadRequest.dns:type_name -> sidecar.DnsConfig
	0,  // 2: sidecar.ProxyConfig.mode:type_name -> sidecar.ProxyMode
	3,  // 3: sidecar.ProxyConfig.nodes:type_name -> sidecar.ProxyNode
	6,  // 4: sidecar.DownloadEvent.log:type_name -> sidecar.LogEvent
	7,  // 5: sidecar.DownloadEvent.progress:type_name -> sidecar.ProgressEvent
	8,  // 6: sidecar.DownloadEvent.state:type_name -> sidecar.StateEvent
	9,  // 7: sidecar.DownloadEvent.error:type_name -> sidecar.ErrorEvent
	10, // 8: sidecar.DownloadEvent.tls_info:type_name -> sidecar.TlsInfo
	11, // 9: sidecar.DownloadEvent.tcp_info:type_name -> sidecar.TcpInfo
	12, // 10: sidecar.DownloadEvent.complete:type_name -> sidecar.CompleteEvent
	17, // 11: sidecar.PresetList.presets:type_name -> sidecar.Preset
	1,  // 12: sidecar.FingerprintDownloader.Download:input_type -> sidecar.DownloadRequest
	13, // 13: sidecar.FingerprintDownloader.Ping:input_type -> sidecar.PingRequest
	15, // 14: sidecar.FingerprintDownloader.GetPresets:input_type -> sidecar.Empty
	5,  // 15: sidecar.FingerprintDownloader.Download:output_type -> sidecar.DownloadEvent
	14, // 16: sidecar.FingerprintDownloader.Ping:output_type -> sidecar.PingResponse
	16, // 17: sidecar.FingerprintDownloader.GetPresets:output_type -> sidecar.PresetList
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_sidecar_proto_init() }
func file_proto_sidecar_proto_init() {
	if File_proto_sidecar_proto != nil {
		return
	}
	file_proto_sidecar_proto_msgTypes[4].OneofWrappers = []any{
		(*DownloadEvent_Log)(nil),
		(*DownloadEvent_Progress)(nil),
		(*DownloadEvent_State)(nil),
		(*DownloadEvent_Error)(nil),
		(*DownloadEvent_TlsInfo)(nil),
		(*DownloadEvent_TcpInfo)(nil),
		(*DownloadEvent_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sidecar_proto_rawDesc), len(file_proto_sidecar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sidecar_proto_goTypes,
		DependencyIndexes: file_proto_sidecar_proto_depIdxs,
		EnumInfos:         file_proto_sidecar_proto_enumTypes,
		MessageInfos:      file_proto_sidecar_proto_msgTypes,
	}.Build()
	File_proto_sidecar_proto = out.File
	file_proto_sidecar_proto_goTypes = nil
	file_proto_sidecar_proto_depIdxs = nil
}
