// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/sidecar.proto

package sidecar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FingerprintDownloader_Download_FullMethodName   = "/sidecar.FingerprintDownloader/Download"
	FingerprintDownloader_Ping_FullMethodName       = "/sidecar.FingerprintDownloader/Ping"
	FingerprintDownloader_GetPresets_FullMethodName = "/sidecar.FingerprintDownloader/GetPresets"
)

// FingerprintDownloaderClient is the client API for FingerprintDownloader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FingerprintDownloaderClient interface {
	// 使用指定的指纹配置发起下载，返回数据流
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadEvent], error)
	// 检查 sidecar 是否存活
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// 获取当前支持的浏览器预设列表
	GetPresets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PresetList, error)
}

type fingerprintDownloaderClient struct {
	cc grpc.ClientConnInterface
}

func NewFingerprintDownloaderClient(cc grpc.ClientConnInterface) FingerprintDownloaderClient {
	return &fingerprintDownloaderClient{cc}
}

func (c *fingerprintDownloaderClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FingerprintDownloader_ServiceDesc.Streams[0], FingerprintDownloader_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DownloadEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FingerprintDownloader_DownloadClient = grpc.ServerStreamingClient[DownloadEvent]

func (c *fingerprintDownloaderClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, FingerprintDownloader_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fingerprintDownloaderClient) GetPresets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PresetList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresetList)
	err := c.cc.Invoke(ctx, FingerprintDownloader_GetPresets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FingerprintDownloaderServer is the server API for FingerprintDownloader service.
// All implementations must embed UnimplementedFingerprintDownloaderServer
// for forward compatibility.
type FingerprintDownloaderServer interface {
	// 使用指定的指纹配置发起下载，返回数据流
	Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadEvent]) error
	// 检查 sidecar 是否存活
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// 获取当前支持的浏览器预设列表
	GetPresets(context.Context, *Empty) (*PresetList, error)
	mustEmbedUnimplementedFingerprintDownloaderServer()
}

// UnimplementedFingerprintDownloaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFingerprintDownloaderServer struct{}

func (UnimplementedFingerprintDownloaderServer) Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadEvent]) error {
	return status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedFingerprintDownloaderServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFingerprintDownloaderServer) GetPresets(context.Context, *Empty) (*PresetList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresets not implemented")
}
func (UnimplementedFingerprintDownloaderServer) mustEmbedUnimplementedFingerprintDownloaderServer() {}
func (UnimplementedFingerprintDownloaderServer) testEmbeddedByValue()                               {}

// UnsafeFingerprintDownloaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FingerprintDownloaderServer will
// result in compilation errors.
type UnsafeFingerprintDownloaderServer interface {
	mustEmbedUnimplementedFingerprintDownloaderServer()
}

func RegisterFingerprintDownloaderServer(s grpc.ServiceRegistrar, srv FingerprintDownloaderServer) {
	// If the following call panics, it indicates UnimplementedFingerprintDownloaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FingerprintDownloader_ServiceDesc, srv)
}

func _FingerprintDownloader_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FingerprintDownloaderServer).Download(m, &grpc.GenericServerStream[DownloadRequest, DownloadEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FingerprintDownloader_DownloadServer = grpc.ServerStreamingServer[DownloadEvent]

func _FingerprintDownloader_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintDownloaderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FingerprintDownloader_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintDownloaderServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FingerprintDownloader_GetPresets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FingerprintDownloaderServer).GetPresets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FingerprintDownloader_GetPresets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FingerprintDownloaderServer).GetPresets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FingerprintDownloader_ServiceDesc is the grpc.ServiceDesc for FingerprintDownloader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FingerprintDownloader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sidecar.FingerprintDownloader",
	HandlerType: (*FingerprintDownloaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FingerprintDownloader_Ping_Handler,
		},
		{
			MethodName: "GetPresets",
			Handler:    _FingerprintDownloader_GetPresets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _FingerprintDownloader_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sidecar.proto",
}
